"""add roles table

Revision ID: 0df8b24f0778
Revises: 10dfe176c186
Create Date: 2026-03-16 21:11:16.242742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df8b24f0778'
down_revision: Union[str, Sequence[str], None] = '10dfe176c186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmPassword', sa.String(length=255), nullable=True))
    op.drop_column('users', 'confirm_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm_password', sa.VARCHAR(length=255, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True))
    op.drop_column('users', 'confirmPassword')
    # ### end Alembic commands ###
