"""add confirm_password

Revision ID: a066bb0155f1
Revises: ba2735aa26f2
Create Date: 2026-03-24 18:03:24.968305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a066bb0155f1'
down_revision: Union[str, Sequence[str], None] = 'ba2735aa26f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirm_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirm_password')
    # ### end Alembic commands ###
